export const dummyThreadListData = [
  {
    id: 1,
    title: 'Новая технология в облачных вычислениях',
    date: '2024-07-01',
    author: 'Иван Иванов',
    authorAvatar: 'https://example.com/avatar1.jpg',
    comments: 120,
  },
  {
    id: 2,
    title: 'Последние достижения в области ИИ',
    date: '2024-06-28',
    author: 'Анна Петрова',
    authorAvatar: 'https://example.com/avatar2.jpg',
    comments: 98,
  },
  {
    id: 3,
    title: 'Будущее квантовых вычислений',
    date: '2024-07-05',
    author: 'Сергей Сидоров',
    authorAvatar: 'https://example.com/avatar3.jpg',
    comments: 76,
  },
  {
    id: 4,
    title: 'Роль больших данных в современной науке',
    date: '2024-07-10',
    author: 'Мария Смирнова',
    authorAvatar: 'https://example.com/avatar4.jpg',
    comments: 54,
  },
  {
    id: 5,
    title: 'Разработка новых методов машинного обучения',
    date: '2024-07-12',
    author: 'Дмитрий Кузнецов',
    authorAvatar: 'https://example.com/avatar5.jpg',
    comments: 87,
  },
  {
    id: 6,
    title: 'Эволюция интернет технологий',
    date: '2024-07-14',
    author: 'Ольга Иванова',
    authorAvatar: 'https://example.com/avatar6.jpg',
    comments: 65,
  },
]
