export const CANVAS_WIDTH = 1080
export const CANVAS_HEIGHT = 720

export const CARD_WIDTH = 100
export const CARD_HEIGHT = 140
export enum CARD_TYPE {
  MELEE = 'MELEE',
  RANGED = 'RANGED',
}

export const DECK_WIDTH = CANVAS_WIDTH
export const DECK_HEIGHT = CANVAS_HEIGHT - CARD_HEIGHT

export const GAME_FIELD_LEFT_INDENT = 200
export const GAME_FIELD_HEIGHT = CANVAS_HEIGHT - CARD_HEIGHT
export const GAME_FIELD_WIDTH = CANVAS_WIDTH - GAME_FIELD_LEFT_INDENT - 5

export const ROW_HEIGHT = (GAME_FIELD_HEIGHT - 15) / 4
export const ROW_SPACING = 5
