export const CANVAS_WIDTH = 1080
export const CANVAS_HEIGHT = 720

export const CARD_WIDTH = 100
export const CARD_HEIGHT = 150

export const DECK_WIDTH = CANVAS_WIDTH
export const DECK_HEIGHT = CANVAS_HEIGHT - CARD_HEIGHT

export const GAME_FIELD_WIDTH = CANVAS_WIDTH - 200
export const GAME_FIELD_HEIGHT = CANVAS_HEIGHT - CARD_HEIGHT
export const GAME_FIELD_LEFT_INDENT = 150

export const ROW_HEIGHT = (GAME_FIELD_HEIGHT - 15) / 4
export const ROW_SPACING = 5
